//! The T6 zone walk: the runtime half. `walk_gen.rs` (generated by
//! `gen/t6gen.py`) holds one load function per asset structure; it calls the
//! primitives here, which implement the game's pointer rules:
//!
//! - an asset header loads into TEMP (when its rules say so), its members
//!   into VIRTUAL; members can name another block;
//! - a pointer is null, "follows" (-1, data next in the stream), "insert"
//!   (-2, follows and is reachable through an alias slot in VIRTUAL; only in
//!   TEMP contexts) or an offset into data loaded earlier;
//! - field references in counts and conditions read the most recently
//!   entered instance of the named structure, as the game's own loader does.

use crate::asset_type::AssetType;
use crate::content::AssetTable;
use crate::walk_gen;
use crate::zone::{Ptr, Result, XFILE_BLOCK_TEMP, ZoneError, ZonePtr, ZoneStream};

const MAX_DEPTH: u32 = 96;

/// One asset load, as the walk saw it.
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub struct Loaded {
    pub ty: AssetType,
    /// Where the asset's header was loaded. For assets whose header goes to
    /// TEMP this is only valid inside `asset_loaded`.
    pub body: Ptr,
    /// The pointer slot that named it (now pointing at `body`).
    pub slot: Ptr,
    /// The VIRTUAL slot later references go through, when the load was an
    /// insert; stable for the whole zone.
    pub alias: Option<Ptr>,
    /// Loads are numbered 1, 2, ... in the order they finish; this is this
    /// load's number.
    pub serial: u64,
    /// The number of loads finished when this one began: nested loads of
    /// this asset have serials above it.
    pub started: u64,
}

/// What a walk reports while it reads; every method has a no-op default.
pub trait WalkSink {
    /// An asset (top-level or nested) finished loading.
    fn asset_loaded(&mut self, s: &ZoneStream<'_>, loaded: Loaded) -> Result<()> {
        let _ = (s, loaded);
        Ok(())
    }

    /// Top-level asset `index` of the asset list is about to load.
    fn begin_asset(&mut self, s: &ZoneStream<'_>, index: usize, ty: AssetType) {
        let _ = (s, index, ty);
    }
}

pub struct NoSink;

impl WalkSink for NoSink {}

pub struct Walker<'w, 'a> {
    pub(crate) s: &'w mut ZoneStream<'a>,
    loads: u64,
    cur: [Ptr; walk_gen::TYPE_COUNT],
    depth: u32,
    trail: [u16; MAX_DEPTH as usize + 1],
    sink: &'w mut dyn WalkSink,
}

/// Field widths the generated code reads for counts and conditions. The
/// current rules never read 64-bit or float fields; the walk keeps them so a
/// regenerated walk can.
#[allow(dead_code)]
#[derive(Clone, Copy)]
pub(crate) enum Kind {
    U8,
    I8,
    U16,
    I16,
    U32,
    I32,
    U64,
    I64,
    F32,
}

impl<'w, 'a> Walker<'w, 'a> {
    pub fn new(s: &'w mut ZoneStream<'a>, sink: &'w mut dyn WalkSink) -> Self {
        Walker {
            s,
            loads: 0,
            cur: [Ptr {
                block: 0,
                offset: 0,
            }; walk_gen::TYPE_COUNT],
            depth: 0,
            trail: [0; MAX_DEPTH as usize + 1],
            sink,
        }
    }

    /// The structures being loaded, outermost first; after a failed walk this
    /// is where it failed.
    pub fn trail(&self) -> impl Iterator<Item = &'static str> + '_ {
        self.trail[..self.depth as usize]
            .iter()
            .map(|&t| walk_gen::TYPE_NAMES[t as usize])
    }

    pub fn stream(&self) -> &ZoneStream<'a> {
        self.s
    }

    pub(crate) fn enter(&mut self, ty: usize, p: Ptr) -> Result<()> {
        self.cur[ty] = p;
        if self.depth >= MAX_DEPTH {
            return Err(ZoneError::WalkTooDeep);
        }
        self.trail[self.depth as usize] = ty as u16;
        self.depth += 1;
        Ok(())
    }

    pub(crate) fn leave(&mut self) {
        self.depth -= 1;
    }

    /// Read a field of the current instance of structure `ty`.
    pub(crate) fn rd(&self, ty: usize, off: usize, kind: Kind) -> Result<i64> {
        self.rd_at(self.cur[ty], off, kind)
    }

    /// Read a field behind a pointer member (at `ptr_off`) of the current
    /// instance of `ty`; the pointee was loaded earlier in the walk.
    pub(crate) fn rd_through(
        &self,
        ty: usize,
        ptr_off: usize,
        off: usize,
        kind: Kind,
    ) -> Result<i64> {
        let raw = self.s.u32_at(self.cur[ty], ptr_off)?;
        match ZonePtr::decode(raw) {
            ZonePtr::Offset(p) => self.rd_at(self.s.resolve_alias(p), off, kind),
            _ => Err(ZoneError::BadPointer {
                what: "count read through an unloaded pointer",
                raw,
            }),
        }
    }

    fn rd_at(&self, p: Ptr, off: usize, kind: Kind) -> Result<i64> {
        Ok(match kind {
            Kind::U8 => self.s.u8_at(p, off)? as i64,
            Kind::I8 => self.s.u8_at(p, off)? as i8 as i64,
            Kind::U16 => self.s.u16_at(p, off)? as i64,
            Kind::I16 => self.s.i16_at(p, off)? as i64,
            Kind::U32 => self.s.u32_at(p, off)? as i64,
            Kind::I32 => self.s.i32_at(p, off)? as i64,
            Kind::U64 => {
                let lo = self.s.u32_at(p, off)? as u64;
                let hi = self.s.u32_at(p, off + 4)? as u64;
                (lo | hi << 32) as i64
            }
            Kind::I64 => {
                let lo = self.s.u32_at(p, off)? as u64;
                let hi = self.s.u32_at(p, off + 4)? as u64;
                (lo | hi << 32) as i64
            }
            Kind::F32 => self.s.f32_at(p, off)? as i64,
        })
    }

    pub(crate) fn count(&self, n: i64) -> Result<usize> {
        if !(0..=0x1000_0000).contains(&n) {
            return Err(ZoneError::BadCount(n));
        }
        Ok(n as usize)
    }

    pub(crate) fn div(a: i64, b: i64) -> Result<i64> {
        if b == 0 {
            return Err(ZoneError::DivideByZero);
        }
        Ok(a / b)
    }

    #[allow(dead_code)]
    pub(crate) fn rem(a: i64, b: i64) -> Result<i64> {
        if b == 0 {
            return Err(ZoneError::DivideByZero);
        }
        Ok(a % b)
    }

    /// Read `size` bytes into the block at `p`, which must be the block's
    /// current write position.
    pub(crate) fn load_at(&mut self, p: Ptr, size: usize) -> Result<()> {
        let top = self.s.top_block()?;
        let pos = self.s.watermark(top as u8);
        if p.block as usize != top || p.offset as usize != pos {
            return Err(ZoneError::NonContiguous {
                block: p.block as usize,
                at: p.offset as usize,
                expected: pos,
            });
        }
        self.s.load_bytes(size)?;
        Ok(())
    }

    pub(crate) fn push(&mut self, block: usize) -> Result<()> {
        self.s.push(block)
    }

    pub(crate) fn pop(&mut self) -> Result<()> {
        self.s.pop()
    }

    #[allow(dead_code)]
    pub(crate) fn ptr(&self, slot: Ptr) -> Result<ZonePtr> {
        self.s.ptr_at(slot, 0)
    }

    /// A pointer that names data loaded earlier.
    fn reuse(&mut self, p: Ptr) {
        self.s.note_offset(p);
    }

    /// The member-pointer rule for single and array pointers and allocated
    /// pointer arrays: null check, optional reuse, allocation, and (in TEMP
    /// contexts) the insert alias. `body` loads the pointee at the
    /// allocation.
    pub(crate) fn member_ptr(
        &mut self,
        slot: Ptr,
        reusable: bool,
        in_temp: bool,
        align: usize,
        body: impl FnOnce(&mut Self, Ptr) -> Result<()>,
    ) -> Result<()> {
        let raw = self.s.u32_at(slot, 0)?;
        let insert = match ZonePtr::decode(raw) {
            ZonePtr::Null => return Ok(()),
            ZonePtr::Following => false,
            ZonePtr::Insert if in_temp => true,
            ZonePtr::Insert => {
                return Err(ZoneError::BadPointer {
                    what: "insert outside a temp block",
                    raw,
                });
            }
            ZonePtr::Offset(p) => {
                if !reusable {
                    return Err(ZoneError::BadPointer {
                        what: "offset on a pointer that never reuses data",
                        raw,
                    });
                }
                self.reuse(p);
                return Ok(());
            }
        };
        let at = self.s.align_alloc(align)?;
        let alias = if insert {
            Some(self.s.insert_pointer_slot()?)
        } else {
            None
        };
        body(self, at)?;
        if let Some(alias) = alias {
            self.s.bind_insert(alias, at)?;
        }
        self.s.fixup_slot(slot, at)
    }

    /// The asset-pointer rule (`LoadPtr` of an asset structure).
    pub(crate) fn asset_ptr(
        &mut self,
        slot: Ptr,
        ty: usize,
        in_temp: bool,
        align: usize,
        load: fn(&mut Self, Ptr, bool) -> Result<()>,
    ) -> Result<()> {
        if in_temp {
            self.push(XFILE_BLOCK_TEMP)?;
        }
        let raw = self.s.u32_at(slot, 0)?;
        match ZonePtr::decode(raw) {
            ZonePtr::Null => {}
            ZonePtr::Following | ZonePtr::Insert => {
                let insert = matches!(ZonePtr::decode(raw), ZonePtr::Insert);
                if insert && !in_temp {
                    return Err(ZoneError::BadPointer {
                        what: "insert on an asset outside a temp block",
                        raw,
                    });
                }
                let at = self.s.align_alloc(align)?;
                let alias = if insert {
                    Some(self.s.insert_pointer_slot()?)
                } else {
                    None
                };
                let started = self.loads;
                load(self, at, true)?;
                self.loads += 1;
                if let Some(alias) = alias {
                    self.s.bind_insert(alias, at)?;
                }
                self.s.fixup_slot(slot, at)?;
                if let Some(asset) = walk_gen::ASSET_OF_TYPE[ty] {
                    let loaded = Loaded {
                        ty: asset,
                        body: at,
                        slot,
                        alias,
                        serial: self.loads,
                        started,
                    };
                    self.sink.asset_loaded(self.s, loaded)?;
                }
            }
            ZonePtr::Offset(p) => self.reuse(p),
        }
        if in_temp {
            self.pop()?;
        }
        Ok(())
    }

    /// One element of a pointer array to a non-asset structure.
    pub(crate) fn elem_ptr(
        &mut self,
        slot: Ptr,
        reusable: bool,
        align: usize,
        body: impl FnOnce(&mut Self, Ptr) -> Result<()>,
    ) -> Result<()> {
        let raw = self.s.u32_at(slot, 0)?;
        match ZonePtr::decode(raw) {
            ZonePtr::Null => Ok(()),
            ZonePtr::Following => {
                let at = self.s.align_alloc(align)?;
                body(self, at)?;
                self.s.fixup_slot(slot, at)
            }
            ZonePtr::Offset(p) if reusable => {
                self.reuse(p);
                Ok(())
            }
            _ => Err(ZoneError::BadPointer {
                what: "pointer-array element",
                raw,
            }),
        }
    }

    /// `LoadXString`: a string pointer that is null, follows, or reuses.
    pub(crate) fn xstring(&mut self, slot: Ptr) -> Result<()> {
        let raw = self.s.u32_at(slot, 0)?;
        match ZonePtr::decode(raw) {
            ZonePtr::Null => Ok(()),
            ZonePtr::Following => {
                let at = self.s.align_alloc(1)?;
                let body = self.s.load_string()?;
                debug_assert_eq!(at, body);
                self.s.fixup_slot(slot, body)
            }
            ZonePtr::Offset(p) => {
                self.reuse(p);
                Ok(())
            }
            ZonePtr::Insert => Err(ZoneError::BadPointer {
                what: "string",
                raw,
            }),
        }
    }

    /// `count` string pointers in a row at `arr`, each loaded in turn.
    pub(crate) fn xstrings(&mut self, arr: Ptr, count: usize) -> Result<()> {
        for i in 0..count {
            self.xstring(arr.at(i * 4))?;
        }
        Ok(())
    }

    /// Walk every asset of an opened asset list in order; leaves the stream
    /// where the last asset ended and pops the list's VIRTUAL block.
    pub fn walk_assets(&mut self, table: &AssetTable) -> Result<()> {
        for i in 0..table.count() {
            let ty = table.kind(self.s, i)?;
            let slot = table.slot(i).ok_or(ZoneError::NoBlockPushed)?;
            self.sink.begin_asset(self.s, i, ty);
            walk_gen::load_xasset(self, ty, slot)?;
        }
        self.s.pop()
    }
}
